### ISSUE TITLE
LMET_train.txt, LMET_valid.txt and LMET_test.txt are missing

### ISSUE THREAD

**Issue by leiloong** [zhiweihu1103/ET-TET#2]
Files about datasets are missing in google drive link https://drive.google.com/drive/folders/120QIGxsGQXfH6Rd8wJe7i57gg8dlx7l2?usp=sharing.  
  train_dataset = ETDataset(args, "LMET_train.txt", e2id, r2id, t2id, c2id, 'train')
    valid_dataset = ETDataset(args, "LMET_valid.txt", e2id, r2id, t2id, c2id, 'valid')
    test_dataset = ETDataset(args, "LMET_test.txt", e2id, r2id, t2id, c2id, 'test')

**Comment by zhiweihu1103** [comment]
Do you not have access to the dataset? I looked at it and the datasets are not missing.

**Comment by zhiweihu1103** [comment]
![image](https://user-images.githubusercontent.com/17820697/197371936-75ee7a4d-d03b-4409-ad21-85222d8e8c28.png)

**Comment by leiloong** [comment]
Notices the LMET_train.**pkl**, LMET_valid.**pkl** and LMET_test.**pkl** instead, sorry for disturb.
A small issue is that the amount of (rclass, c) info for some entities in LMET_train.**pkl** are slightly larger than type info of these entities in ET_train.txt, should we remove it and re-pickle these files before training?

**Comment by zhiweihu1103** [comment]
First, the LMET_train.pkl, LMET_valid.pkl and LMET_test.pkl are from LMET_train.txt, LMET_valid.txt and LMET_test.txt, If *.pkl does not exist, it will be created automatically, as shown in the following code：
https://github.com/zhiweihu1103/ET-TET/blob/18bf33362b48313aadbf752a0ca731c8efa3579e/dataloader.py#L27
Second, you don't need to do any other processing operations other than the code I provided, because the connection content of the knowledge graph itself is used, so it is normal for the number to increase.

**Comment by leiloong** [comment]
got it, thx a lot.
